version: "3.9"

services:

#  nginx:
#    image: nginx:1.25-alpine
#    container_name: rinha2025-nginx
#    volumes:
#      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
#    depends_on:
#      - api1
#      - api2
#    ports:
#      - "9999:9999"
#    networks:
#      - backend
#      - payment-processor
#    deploy:
#      resources:
#        limits:
#          cpus: "0.15"
#          memory: "15MB"

  backendDB:
    image: postgres:17-alpine
    container_name: backendDB
    hostname: backendDB
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=backendDB
    ports:
      - "5432:5432"
    volumes:
      - "./.docker/data/backendDB:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "backendDB"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "250MB"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true