amqp:
  host: ${AMQP_RABBIT_HOST:localhost}
  port: ${AMQP_RABBIT_PORT:5672}
  username: ${AMQP_RABBIT_USERNAME:admin}
  password: ${AMQP_RABBIT_PASSWORD:admin}
  admin:
    auto-create: ${AMQP_ADMIN_AUTO_CREATE:false}
  queues:
    payment-processor-created:
      exchange: payment.processor.events
      routing-key: payment.processor.created
      queue: payment.processor.queue

server:
  port: ${PORT:8082}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  tomcat:
    threads:
      max: ${MAX_POOL_CONNECTION:4}
    max-connections: ${MAX_POOL_CONNECTION:4}

spring:
  application:
    name: makersgateway
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/${DB_NAME:backendDB}
    username: ${DB_USER:backend}
    password: ${DB_PASS:backend}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: ${MAX_POOL_CONNECTION:4}
      minimum-idle: 10
      pool-name: master
    tomcat:
      max-active: ${MAX_POOL_CONNECTION:5}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    dynamic: ${amqp.admin.auto-create}
    host: ${amqp.host}
    port: ${amqp.port}
    username: ${amqp.username}
    password: ${amqp.password}
  servlet:
    multipart:
      max-file-size: 10MB # Max file size.
      max-request-size: 5MB # Max request size.

logging:
  level:
    root: ${LOG_LEVEL:INFO}